version: '3.9'
services:
  postgres:
    image: postgres :16-alpine
    container_name: event_ticketing_db
    restart: unless-stopped


    enviroment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "${DB_PORT}:5432"

    volumes:
      - event_ticketing_pgdata:/var/lib/postgresql/data
  
  volumes:
    event_ticketing_pgdata:
    